var translation = {
  'Greatest Common Divisor': '最大公约数',
  'G.C.D': '最大公约数',

  'Mode': '模式',
  'Difficulty': '难度',
  'Language': '语言',
  'Achievements': '成就',
  'Clear Score': '清空记录',
  'Easy': '简单',
  'Hard': '困难',

  'Top Score': '最高分',
  'Best Combo': '最佳组合',
  'Max GCD': '最大公约数',
  'Max Power': '最多公约数量',
  'Max Turn': '最长回合',
  'Total Round': '总游玩次数',

  'Prime Liker': '质数爱好者',
  'Prime Hater': '合数爱好者',
  'One': '一',
  'One Seeker': '8 个一',
  'One Maniac': '12 个一',
  'Colorless': '纯白',
  'Coprime Doom': '互质之王',
  'Power': '指数',
  'Octadic': '一半能约',
  'A Dozen': '一打能约',
  'Grand Slam': '一网打尽',
  'Divisor': '公因数',
  'Divisor Rookie': '公因数超过 20',
  'Divisor Veteran': '公因数超过 40',
  'Divisor Master': '公因数超过 60',
  'Equalitarian': '相等',
  'Equalitarian Rookie': '四重奏',
  'Equalitarian Veteran': '六重奏',
  'Equalitarian Master': '同归于尽',
  'Factorization': '因数分解',
  'Factorization Rookie': '五颜六色',
  'Factorization Veteran': '五花八门',
  'Factorization Master': '百花齐放',
  'GCD': '最高分',
  'GCD Rookie':   '最高分 10000',
  'GCD Veteran':  '最高分 100000',
  'GCD Master':   '最高分 1000000',
  'GCD Emperor':  '最大公约数之王',
  'Rejuvenated': '起死回生',
  'Bloody': '血染的风采',
  'Composite Successor': '合数继承者',
  'Quadruplication': '一分为四',
  'Unshakable': '一一得一',
  'Turn': '回合',
  'Libido': '100 回合',
  'Longevous': '500 回合',
  'Immortal': '长生不老'
};